require: rubocop-rspec

Rails:
  Enabled: true
  
AllCops:
  UseCache: false
  DisplayCopNames: true
  Include:
    - '**/Rakefile'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
